ISSUE#5 - Enhancement for better reporting

diff --git a/.github/workflows/github-actions-unitTest.yml b/.github/workflows/github-actions-unitTest.yml
--- a/.github/workflows/github-actions-unitTest.yml
+++ b/.github/workflows/github-actions-unitTest.yml
@@ -16,6 +16,17 @@ jobs:
           node-version: 16
           cache: 'npm'
       - name: Run JUnit with Maven
-        run: mvn clean test
+        run: mvn test --batch-mode --fail-at-end
       - name: Run Jest with NPM
         run: npm test
+      - name: Surefire Report
+        if: success() || failure()    # run this step even if previous step failed
+        uses: ScaCap/action-surefire-report@v1.0.5
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.5.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: target/test-results/TESTS-results-jest.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
+
